// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqazfwlwlatzmaibbvrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxYXpmd2x3bGF0em1haWJidnJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTAzNTcsImV4cCI6MjA2ODMyNjM1N30.yjG25QFGOQevsQm9PjaZTXLTOAqwZ9xrZMqMfNeRCe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});